export const LOCAL_MEME_MANIFEST = [
  {
    id: 'salim_kumar_confused',
    name: 'Confused Disbelief',
    asset: '/assets/memes/salim_kumar_confused.svg',
    category: 'confused',
    difficulty: 2,
    origin: 'malayalam_cinema',
    targetFeatures: {
      expressions: ['head_turn', 'eyebrow_raise'],
      gestures: ['facepalm'],
      pose: [],
      checklist: [
        { key: 'head_turn', label: 'Turn Head Side 🤨' },
        { key: 'facepalm', label: 'Hand Near Face 🤦' },
      ],
    },
  },
  {
    id: 'salim_kumar_smug',
    name: 'Cocky Smug Smirk',
    asset: '/assets/memes/salim_kumar_smug.svg',
    category: 'sass',
    difficulty: 2,
    origin: 'malayalam_cinema',
    targetFeatures: {
      expressions: ['smile', 'eyebrow_raise'],
      gestures: [],
      pose: [],
      checklist: [
        { key: 'smile', label: 'Smug Smirk 😏' },
        { key: 'head_turn', label: 'Head Tilt / Turn 🤨' },
      ],
    },
  },
  {
    id: 'jagathy_suspicious',
    name: 'Suspicious Side-Eye',
    asset: '/assets/memes/jagathy_suspicious.svg',
    category: 'suspicious',
    difficulty: 2,
    origin: 'malayalam_cinema',
    targetFeatures: {
      expressions: ['squint', 'head_turn'],
      gestures: [],
      pose: [],
      checklist: [
        { key: 'squint', label: 'Squint Eye 👁️' },
        { key: 'head_turn', label: 'Side-Eye Turn 🤨' },
      ],
    },
  },
  {
    id: 'fahadh_shammi_smug',
    name: 'Unblinking Stare',
    asset: '/assets/memes/fahadh_shammi_smug.svg',
    category: 'unhinged',
    difficulty: 3,
    origin: 'malayalam_cinema',
    targetFeatures: {
      expressions: ['smile', 'wide_eyes'],
      gestures: [],
      pose: [],
      checklist: [
        { key: 'wide_eyes', label: 'Wide Unblinking Stare 😳' },
        { key: 'smile', label: 'Slight Eerie Smile 🙂' },
      ],
    },
  },
  {
    id: 'open_mouth',
    name: 'Shocked Jaw Drop',
    asset: '/assets/memes/open_mouth.jpeg',
    category: 'shocked',
    difficulty: 1,
    origin: 'international',
    targetFeatures: {
      expressions: ['open_mouth'],
      gestures: [],
      pose: [],
      checklist: [{ key: 'open_mouth', label: 'Open Mouth 😮' }],
    },
  },
  {
    id: 'cover_nose',
    name: 'Facepalm Reaction',
    asset: '/assets/memes/cover_nose.jpeg',
    category: 'dramatic',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: [],
      gestures: ['facepalm'],
      pose: [],
      checklist: [{ key: 'facepalm', label: 'Hand Over Face 🤦' }],
    },
  },
  {
    id: 'crashing_out',
    name: 'Screaming Chaos',
    asset: '/assets/memes/crashing_out.jpeg',
    category: 'chaos',
    difficulty: 3,
    origin: 'international',
    targetFeatures: {
      expressions: ['open_mouth'],
      gestures: ['hands_up'],
      pose: ['elbows_up'],
      checklist: [
        { key: 'open_mouth', label: 'Scream / Open Mouth 😮' },
        { key: 'hands_up', label: 'Hands Raised 🙌' },
      ],
    },
  },
  {
    id: 'dance',
    name: 'Vibes Dance',
    asset: '/assets/memes/dance.jpeg',
    category: 'chaos',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: [],
      gestures: ['open_palm'],
      pose: ['elbows_up'],
      checklist: [
        { key: 'elbows_up', label: 'Elbows Raised 🕺' },
        { key: 'open_palm', label: 'Open Palms 🖐️' },
      ],
    },
  },
  {
    id: 'disgusted',
    name: 'Disgusted Sneer',
    asset: '/assets/memes/disgusted.jpeg',
    category: 'sass',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: ['sneer'],
      gestures: [],
      pose: [],
      checklist: [{ key: 'sneer', label: 'Nose Sneer / Disgust 🤢' }],
    },
  },
  {
    id: 'flirty',
    name: 'Flirty Wink',
    asset: '/assets/memes/flirty.jpeg',
    category: 'flirty',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: ['wink', 'smile'],
      gestures: [],
      pose: [],
      checklist: [
        { key: 'wink', label: 'Wink Eye 😉' },
        { key: 'smile', label: 'Smile 😊' },
      ],
    },
  },
  {
    id: 'hand_up',
    name: 'Talk to the Hand',
    asset: '/assets/memes/hand_up.jpeg',
    category: 'sass',
    difficulty: 1,
    origin: 'international',
    targetFeatures: {
      expressions: [],
      gestures: ['hand_up'],
      pose: [],
      checklist: [{ key: 'hand_up', label: 'Hand Up / Stop 🖐️' }],
    },
  },
  {
    id: 'heart',
    name: 'Heart Hands',
    asset: '/assets/memes/heart.jpeg',
    category: 'wholesome',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: ['smile'],
      gestures: ['heart'],
      pose: [],
      checklist: [
        { key: 'heart', label: 'Heart Hands 🫶' },
        { key: 'smile', label: 'Warm Smile 😊' },
      ],
    },
  },
  {
    id: 'nose_closed',
    name: 'Pinch Nose',
    asset: '/assets/memes/nose_closed.gif',
    category: 'sass',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: [],
      gestures: ['pinch_nose'],
      pose: [],
      checklist: [{ key: 'pinch_nose', label: 'Pinch Nose 🤌' }],
    },
  },
  {
    id: 'suspicious',
    name: 'Suspicious Side-Eye',
    asset: '/assets/memes/suspicious.jpeg',
    category: 'suspicious',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: ['squint', 'head_turn'],
      gestures: [],
      pose: [],
      checklist: [
        { key: 'head_turn', label: 'Turn Head 🤨' },
        { key: 'squint', label: 'Squint Eye 👀' },
      ],
    },
  },
  {
    id: 'time_out',
    name: 'Time Out T-Sign',
    asset: '/assets/memes/time_out.jpeg',
    category: 'confused',
    difficulty: 2,
    origin: 'international',
    targetFeatures: {
      expressions: [],
      gestures: ['time_out'],
      pose: [],
      checklist: [{ key: 'time_out', label: 'Time Out T-Sign 🙅' }],
    },
  },
  {
    id: 'tongue_out',
    name: 'Silly Tongue Out',
    asset: '/assets/memes/tongue_out.jpeg',
    category: 'unhinged',
    difficulty: 1,
    origin: 'international',
    targetFeatures: {
      expressions: ['tongue_out'],
      gestures: [],
      pose: [],
      checklist: [{ key: 'tongue_out', label: 'Stick Tongue Out 😛' }],
    },
  },
]
